config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "categories#index"
  resources :categories
  resources :photos
  resources :comments
  get "/page_search", to: "photos#page_search"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  # *validation
  validates :name, presence: true, uniqueness: true
  validates :cover, presence: true
  # validates :cover, presence: true
  validates :description, length: { maximum: 300, message: " should be at least 300 characters" }


  # *association
  has_many :photos, dependent: :destroy
  # pholymorphic
  has_many :comments, as: :commentable, dependent: :destroy
  has_one_attached :cover
end

app/models/comment.rb
class Comment < ApplicationRecord
  # *validation
  validates :body, presence: true

  # *association
  belongs_to :commentable, polymorphic: true
  # belongs_to :photo, counter_cache: true

  # Callback
  after_create :increment_photos_count
  after_destroy :decrement_photos_count

  private

  def increment_photos_count
    return unless commentable.is_a?(Photo)

    comment_photo = commentable
    comment_photo.comments_count += 1
    comment_photo.save
  end

  def decrement_photos_count
    return unless commentable.is_a?(Photo)

    comment_photo = commentable
    comment_photo.comments_count -= 1
    comment_photo.save
  end
end

app/models/photo.rb
class Photo < ApplicationRecord
  # *validation
  validates :title, presence: true, uniqueness: true
  validates :image, presence: true
  validates :description, length: { maximum: 300, message: " should be maximum 300 characters" }

  # *association
  belongs_to :category, counter_cache: true
  # *Polymorphics
  has_many :comments, as: :commentable, dependent: :destroy
  has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.order(id: :asc)
  end

  def new
    @category = Category.new
  end

  def show
    @category = Category.find(params[:id])
    @photos = @category.photos.order(id: :asc)
    @comments = @category.comments
  end

  def create
    @category = Category.create(category_param)
    if @category.save
      redirect_to categories_path
    else
      render "new", status: :unprocessable_entity
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_param)
      redirect_to categories_path
    else
      render "edit", status: :unprocessable_entity
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path, status: :see_other
  end

  private

  def category_param
    params.require(:category).permit(:name, :description, :cover)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    if params[:photo_id]
      @photo = Photo.find(params[:photo_id])
      @comment = @photo.comments.create(body: params[:body])
      if @comment.save
        redirect_to photo_path(@photo)
      else
        redirect_to photo_path(@photo), status: :unprocessable_entity
      end
    elsif params[:category_id]
      @category = Category.find(params[:category_id])
      @comment = @category.comments.create(body: params[:body])
      if @comment.save
        redirect_to category_path(@category)
      else
        # puts " ================================="
        # render "new", status: :unprocessable_entity
        redirect_to category_path(@category), status: :unprocessable_entity
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    if params[:photo_id]
      @photo = Photo.find(params[:photo_id])
      @comment.destroy
      redirect_to photo_path(@photo), status: :see_other
    else
      @category = Category.find(params[:category_id])
      @comment.destroy
      redirect_to category_path(@category), status: :see_other
    end
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index; end

  def new
    @photo = Photo.new
    @category = Category.find(params[:category_id])
  end

  def show
    @photo = Photo.find(params[:id])
    @comment = Comment.new
    @comments = @photo.comments
    @category = Category.find(@photo[:category_id])
  end

  def create
    @photo = Photo.create(photo_params)
    if @photo.save
      redirect_to category_path(@photo.category)
    else
      @category = Category.find(params["photo"]["category_id"])
      render "new", status: :unprocessable_entity
    end
  end

  def edit
    @photo = Photo.find(params[:id])
    @category = Category.find(params[:category_id])
  end

  def update
    @photo = Photo.find(params[:id])
    if @photo.update(photo_params)
      redirect_to category_path
    else
      @category = Category.find(params["photo"]["category_id"])
      render "edit", status: :unprocessable_entity
    end
  end

  def destroy
    @photo = Photo.find(params[:id])
    @category = Category.find(params[:category_id])
    @photo.destroy
    redirect_to category_path(@category), status: :see_other
  end

  def page_search
    puts "-------------------------"
    puts "Parametrossss"
    p params
    puts "-------------------------"
    @photos_found = []
    @empty = false
    @no_results = false
    if params[:search]
      return if params[:search].nil?

      @empty = true if params[:search].empty?

      unless @empty
        query = params[:search].downcase
        @photos_found = Photo.where("LOWER(title) LIKE ?", "%#{query}%")

        @no_results = true if @photos_found.length.zero?

      end
    end
  end

  private

  def photo_params
    params.require(:photo).permit(:title, :description, :image, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/categories/_form.html.erb
<%=form_with model: category, class: "flex flex-column gap-4 mb-4" do |f|%>
      <div class="input">
        <%=f.label :name, class: "content-xs overline"%>
        <div class="<%= @category.errors.full_messages[0] && 'border-error'%> input__container">
          <%=f.text_field :name, placeholder: 'Technology', class: "input__content"%>
        </div>        
      </div>

      <div class="input">
        <%=f.label :description, class: "content-xs overline"%>
        <div class="input__container">
          <%=f.text_area :description, placeholder: 'Exploring our complicated relationship with technology...', class: "input__content"%>
        </div>
      </div>

      <div>
        <%=f.label :cover, class: "content-xs overline"%>
        <div>
          <%=f.file_field :cover, accept: "image/png, image/jpeg"%>
        </div>
      </div>

      <%=f.submit class: "button button--secondary"%>
    <%end%>

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb
<section class="section">
  <div class="container">
    <h1 class="heading mb-4">Edit Category</h1>
     <%if @category.errors.any?%>
    	<h2 class = "error heading--xs">Something went wrong:</h2>
      <div class = "mb-4">
        <ul class = "reset-ul">
          <%@category.errors.full_messages.each do |message|%>
            <li><%=message%></li>
          <%end%>
        </ul>
      </div>
    <%end%>
    <%=render "form", category: @category%>

    <%=link_to "Back", categories_path, class: "button button--subtle"%>
  </div>
</section>

app/views/categories/index.html.erb
<section class="section-md">
  <div class="container">
    <h1 class="heading mb-4">Categories</h1>
    <%=link_to "New category", new_category_path, class: "button button--secondary button--sm mb-4 fit-content"%>
    
    <div class="card-list">
      <% if @categories.length > 0  %>

        <%@categories.each do |category|%>
          <div class="category-card">
            <%if category.cover.attached?%>
                <%=image_tag category.cover, class: "category-card__image"%>
            <%end%>
            <div class="category-card__content">
              <%=link_to category.name, category_path(category), class: "heading--sm regular"%>
              <span class="content-sm"><%=category.photos_count%> photos</span>
              <p><%=category.description%></p>
            </div>
            <div class="category-card__links">
              <div>
              <%= link_to image_tag("edit-button.svg", class: "button__link"), edit_category_path(category) %>
              </div>
              <div>
              <%= link_to image_tag("delete-button.svg", class: "button__link"), category_path(category), data: { turbo_method: :delete, turbo_confirm: "Sure?" } %>
              </div>
            </div>
          </div>
        <%end%>

      <% else %>

        <div class="empty__container">
          No Categories to show. Please add some categories 😀​📷​
        </div>

      <% end %>
    </div>
  </div>
</section>

app/views/categories/new.html.erb
<section class="section-md">
  <div class="container">
    <h1 class="heading mb-4">New Category</h1>
     <%if @category.errors.any?%>
    	<h2 class = "error heading--xs">Something went wrong:</h2>
      <div class = "mb-4">
        <ul class = "reset-ul">
          <%@category.errors.full_messages.each do |message|%>
            <li><%=message%></li>
          <%end%>
        </ul>
      </div>
    <%end%>

    <%=render "form", category: @category%>

    <%=link_to "Back", categories_path, class: "button button--subtle"%>
  </div>
</section>

app/views/categories/show.html.erb
<section class="section">
  <div class="container">
    <h1 class="heading mb-4"><%=@category.name%></h1>
    <p class="mb-4"><%=@category.description%></p>

    <%=link_to "New photo", new_photo_path(category_id: @category.id),
    class: "button button--secondary mb-4 button--sm fit-content" %>

    <div class="flex flex-column ">
      <% if @photos.length > 0  %>

        <%@photos.each do |photo|%>
          <div class="photo-card">
            <%if photo.image.attached?%>
                <%=image_tag photo.image, class: "photo-card__image"%>
            <%end%>
            <div class="photo-card__content">
              <%=link_to photo.title, photo_path(photo), class: "heading--sm regular" %>
              <div class="photo-card__base">
                <div class="content-sm"><%=photo.comments_count%> comments</div>
                <div class="photo-card__options">
                  <div><%= link_to image_tag("edit-button.svg", class: "button__link"), edit_photo_path(photo, category_id: @category.id)%>
                  </div>
                  <div><%= link_to image_tag("delete-button.svg", class: "button__link"), photo_path(photo, category_id: @category.id), data: { turbo_method: :delete, turbo_confirm: "Sure?" } %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <%end%>

        <%# -------------FORM---------------------%>
        <%=form_with url: comments_path(category_id: @category.id), class: "flex flex-column gap-4 mb-4" do |f|%>
          <div class="input">
            <div class="input__container">
              <%=f.text_area :body, class: "input__content", placeholder: "Some respectul commet here."%>
            </div>
          </div>
          <%=f.submit class: "button button--secondary", value: "Comment"%>
        <%end%>

        <%# -------------COMMENTS---------------------%>
        <p class="heading--xs regular mb-4">Comments</p>
        <%@comments.each do |comment|%>
        <div class="comment__container">
          <div class="break__line"></div>
          <p class="content-base"><%= comment.body%></p>
          <div class="comment-options">
          <p class="content-sm" style="color: var(--gray-200);">Send <%=time_ago_in_words(comment.created_at)%> ago</p>
            <%= link_to image_tag("delete-button.svg", class: "button__link"), comment_path(comment, category_id: @category.id) , data: { turbo_method: :delete, turbo_confirm: "Sure?" } %>
            </div>
        </div>
        <%end%> 

        <%=link_to "Back to categories", categories_path%>
      <% else %>

        <div class="empty__container">
          No photos in this category. Please add some photos 😀​📷​
        </div>

      <% end %>

    </div>
  </div>
</section>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SomesplashW9exC7Team3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header class="header">
        <%= link_to image_tag("logo_somesplash.png"), categories_path %>
        <%=link_to "Search", "/page_search", class: "button button--secondary button--sm"%>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <div class="footer footer__content">
        <h3>Build with ♥ by</h3>
        <div class="footer--names">
          <div class="footer__member-tag">Christhian Silupú</div>
          <div class="footer__member-tag">David Montoya</div>
          <div class="footer__member-tag">Dik Solis </div>
          <div class="footer__member-tag">Felix Palacios</div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/photos/_form.html.erb
<%=form_with model: photo, class: "flex flex-column gap-4 mb-4" do |f|%>
      <div class="input">
        <%=f.label :title, class: "content-xs overline"%>
        <div class="<%='border-error' if @photo.errors.any? %> input__container">
          <%=f.text_field :title, placeholder: 'Big mountain', class: "input__content"%>
        </div>
      </div>

      <div class="input">
        <%=f.label :description, class: "content-xs overline"%>
        <div class="input__container">
          <%=f.text_area :description, placeholder: 'Photo taken on...', class: "input__content"%>
        </div>
      </div>

      <div class="select">
        <%=f.label :category_id, class: "content-xs overline" %>
        <%= f.collection_select :category_id, Category.order(:name), :id, :name, { selected: category.id }, class: "select__input" %>
       </div>

      <div>
        <%=f.label :image, class: "content-xs overline"%>
        <div>
          <%=f.file_field :image, accept: "image/png, image/jpeg"%>
        </div>
      </div>

      <%=f.submit class: "button button--secondary"%>
    <%end%>

app/views/photos/create.html.erb
<h1>Photos#create</h1>
<p>Find me in app/views/photos/create.html.erb</p>

app/views/photos/destroy.html.erb
<h1>Photos#destroy</h1>
<p>Find me in app/views/photos/destroy.html.erb</p>

app/views/photos/edit.html.erb
<section class="section">
  <div class="container">
    <h1 class="heading mb-4">Edit Photo</h1>
    <%if @photo.errors.any?%>
    	<h2 class = "error heading--xs">Something went wrong:</h2>
      <div class = "mb-4">
        <ul class = "reset-ul">
          <%@photo.errors.full_messages.each do |message|%>
            <li><%=message%></li>
          <%end%>
        </ul>
      </div>
    <%end%>

    <%=render "form", photo: @photo, category: @category%>

    <%=link_to "Back", categories_path, class: "button button--subtle"%>
  </div>
</section>

app/views/photos/index.html.erb
<h1>Photos#index</h1>
<p>Find me in app/views/photos/index.html.erb</p>

app/views/photos/new.html.erb
<section class="section-md">
  <div class="container">
    <h1 class="heading mb-4">New Photo</h1>
     <%if @photo.errors.any?%>
    	<h2 class = "error heading--xs">Something went wrong:</h2>
      <div class = "mb-4">
        <ul class = "reset-ul">
          <%@photo.errors.full_messages.each do |message|%>
            <li><%=message%></li>
          <%end%>
        </ul>
      </div>
    <%end%>

    <%=render "form", photo: @photo, category: @category%>

    <%=link_to "Back", category_path(@category), class: "button button--subtle"%>
  </div>
</section>

app/views/photos/page_search.html.erb
<section class="section">
  <div class="container">
    <h2 class="heading mb-4">Search</h2>
    <%=form_tag("/page_search", :method => "get", class: "flex flex-column gap-4 mb-4" ) do %>
      <div class="input">
        <div class= "<%= @empty ? 'border-error' : 'normal-class' %> input__container">
          <%=text_field_tag :search, '', class: "input__content", placeholder: "Search term"%>
        </div>        
      </div>

      <%=submit_tag "Search Photos", class: "button button--secondary"%>
    <%end%>

    <% if @empty %>
      <p class = "center-text" > You must enter a search term </p>
      <% else %>
        <% if @photos_found.length.positive? %>
          <p class = ""><%=@photos_found.length == 1 ? "#{@photos_found.length} photo found" : "#{@photos_found.length} photos found" %> </p>
          <%@photos_found.each do |photo|%>
            <div class="photo-card">
              <%if photo.image.attached?%>
                  <%=image_tag photo.image, class: "photo-card__image"%>
              <%end%>
              <div class="photo-card__content">
                <%=link_to photo.title, photo_path(photo), class: "heading--sm regular" %>
                <span class="content-sm"><%=photo.comments_count%> comments</span>
              </div>
              <div class="photo-card__links">
                <div>
                <%= link_to image_tag("edit-button.svg", class: "button__link"), edit_photo_path(photo, category_id: photo.category_id)%>
                </div>
                <div>
                <%= link_to image_tag("delete-button.svg", class: "button__link"), photo_path(photo, category_id: photo.category_id), data: { turbo_method: :delete, turbo_confirm: "Sure?" } %>
                </div>
              </div>
            </div>
          <%end%>
        
        <% else %>
          <% if @no_results %>
            <p class = "center-text" > No results found, please try another search :c </p>
          <% end %>
        <% end %>
    <% end %>
    
  </div>
</section>

app/views/photos/show.html.erb
<section class="section">
  <div class="container">
    <h1 class="heading"><%=@photo.title%></h1>
    <p><%=@photo.description%></p>
    <p class="content-sm" style="color: var(--gray-200);">Updated at <%=time_ago_in_words(@photo.updated_at)%> ago</p>
    <%=image_tag @photo.image, class: "photo__image" %> 
    <%= form_with url: comments_path(photo_id: @photo.id), class: "flex flex-column gap-4 mb-4" do |f| %>
    <div class="input">
      <div class="input__container">
        <%=f.text_area :body, class: "input__content"%>
      </div>
    </div>
    <%=f.submit class: "button button--secondary", value: "Comment"%> 
    <%end%>
    <p class="heading--xs regular mb-4">Comments</p>
    <%@comments.each do |comment|%>
    <div class="comment__container">
      <div class="break__line"></div>
      <p class="content-base"><%= comment.body%></p>
      <div class="comment-options">
      <p class="content-sm" style="color: var(--gray-200);">Send <%= time_ago_in_words(comment.created_at)%> ago</p>
        <%= link_to image_tag("delete-button.svg", class: "button__link"), comment_path(comment, photo_id: @photo.id) , data: { turbo_method: :delete, turbo_confirm: "Sure?" } %>
        </div>
    </div>
    <%end%> 
    <%=link_to "Back to categories", category_path(@category)%>
  </div>
</section>

app/views/photos/update.html.erb
<h1>Photos#update</h1>
<p>Find me in app/views/photos/update.html.erb</p>